"""Tests for promote_agents: generate_alias_dirs / cleanup_auto_generated."""

import textwrap
from pathlib import Path

import pytest
import yaml

from adkx import generate_alias_dirs, cleanup_auto_generated
from adkx.promote import _AUTO_GENERATED_MARKER


FIXTURES = Path(__file__).resolve().parent / "promote_agents"


class TestGenerateAliasDirs:
    """Verify generate_alias_dirs produces correct aliases for each pattern."""

    def _run(self, tmp_path: Path, fixture_name: str) -> list[Path]:
        """Copy fixture to tmp_path and run generate_alias_dirs."""
        import shutil
        agents_dir = tmp_path / "agents"
        shutil.copytree(FIXTURES / fixture_name, agents_dir / fixture_name)
        return generate_alias_dirs(agents_dir)

    # --- a1: simple sub-agent ---
    def test_a1_simple_agent(self, tmp_path):
        generated = self._run(tmp_path, "a1_simple_agent")
        assert len(generated) == 1
        alias_dir = generated[0]
        assert alias_dir.name == "a1_simple_agent_greet_agent"
        assert (alias_dir / _AUTO_GENERATED_MARKER).exists()
        assert (alias_dir / "__init__.py").exists()
        assert (alias_dir / ".adk" / "preset.yaml").exists()

        with open(alias_dir / ".adk" / "preset.yaml") as f:
            preset = yaml.safe_load(f)
        assert preset["agent_path"] == "a1_simple_agent.agent.greet_agent"

    # --- a2: agent with tools ---
    def test_a2_with_tools(self, tmp_path):
        generated = self._run(tmp_path, "a2_with_tools")
        assert len(generated) == 1
        alias_dir = generated[0]
        assert alias_dir.name == "a2_with_tools_greet_agent"

        with open(alias_dir / ".adk" / "preset.yaml") as f:
            preset = yaml.safe_load(f)
        assert preset["agent_path"] == "a2_with_tools.agent.greet_agent"

    # --- a3: sub-agent in a different file ---
    def test_a3_another_file(self, tmp_path):
        generated = self._run(tmp_path, "a3_another_file")
        assert len(generated) == 1
        alias_dir = generated[0]
        assert alias_dir.name == "a3_another_file_greet_agent"

        with open(alias_dir / ".adk" / "preset.yaml") as f:
            preset = yaml.safe_load(f)
        assert preset["agent_path"] == "a3_another_file.sub_agent.greet_agent"

    # --- a4: sub-agent in a subfolder ---
    def test_a4_another_folder(self, tmp_path):
        generated = self._run(tmp_path, "a4_another_folder")
        assert len(generated) == 1
        alias_dir = generated[0]
        assert alias_dir.name == "a4_another_folder_greet_agent"

        with open(alias_dir / ".adk" / "preset.yaml") as f:
            preset = yaml.safe_load(f)
        assert preset["agent_path"] == "a4_another_folder.sub_agents.greet_agent.greet_agent"

    # --- a5: multiple sub-agents ---
    def test_a5_multiple_agent(self, tmp_path):
        generated = self._run(tmp_path, "a5_multiple_agent")
        assert len(generated) == 2, f"Expected 2 aliases, got {len(generated)}: {[d.name for d in generated]}"

        names = sorted(d.name for d in generated)
        assert names == [
            "a5_multiple_agent_cat_agent",
            "a5_multiple_agent_dog_agent",
        ]

        # Verify agent_path for each alias
        for alias_dir in generated:
            assert (alias_dir / _AUTO_GENERATED_MARKER).exists()
            assert (alias_dir / "__init__.py").exists()
            with open(alias_dir / ".adk" / "preset.yaml") as f:
                preset = yaml.safe_load(f)
            if alias_dir.name == "a5_multiple_agent_cat_agent":
                assert preset["agent_path"] == "a5_multiple_agent.cat_agent.cat_agent"
            else:
                assert preset["agent_path"] == "a5_multiple_agent.sub_agents.dog_agent.dog_agent"


class TestCleanupAutoGenerated:
    """Verify cleanup_auto_generated only removes auto-generated directories."""

    def test_cleanup_removes_auto_generated(self, tmp_path):
        agents_dir = tmp_path / "agents"
        agents_dir.mkdir()

        # Create an auto-generated directory
        auto_dir = agents_dir / "auto_alias"
        auto_dir.mkdir()
        (auto_dir / _AUTO_GENERATED_MARKER).write_text("auto")
        (auto_dir / "__init__.py").write_text("# auto")

        # Create a normal directory
        normal_dir = agents_dir / "normal_agent"
        normal_dir.mkdir()
        (normal_dir / "__init__.py").write_text("# normal")

        cleanup_auto_generated(agents_dir)

        assert not auto_dir.exists(), "Auto-generated dir should be removed"
        assert normal_dir.exists(), "Normal dir should NOT be removed"

    def test_cleanup_on_empty_dir(self, tmp_path):
        agents_dir = tmp_path / "agents"
        agents_dir.mkdir()
        cleanup_auto_generated(agents_dir)  # should not raise
