"""Promote agents: auto-generate alias directories from preset.yaml.

Reads the ``promote_agents`` section of each agent's preset.yaml and
creates lightweight alias directories that re-export the sub-agent as a
top-level adk web application.

Generated directories are marked with an ``.auto_generated`` sentinel
file and cleaned up automatically when the server shuts down.
"""

from __future__ import annotations

import logging
import shutil
import textwrap
from pathlib import Path

import yaml

from adkx.config import find_preset_file, load_raw_yaml

logger = logging.getLogger(__name__)

# Sentinel file placed inside auto-generated directories.
_AUTO_GENERATED_MARKER = ".auto_generated"


def _find_auto_generated_dirs(agents_dir: Path) -> list[Path]:
    """Return auto-generated alias directories inside *agents_dir*."""
    dirs: list[Path] = []
    if not agents_dir.is_dir():
        return dirs
    for d in agents_dir.iterdir():
        if d.is_dir() and (d / _AUTO_GENERATED_MARKER).exists():
            dirs.append(d)
    return dirs


def cleanup_auto_generated(agents_dir: Path) -> None:
    """Remove all auto-generated alias directories."""
    for d in _find_auto_generated_dirs(agents_dir):
        try:
            shutil.rmtree(d)
            logger.info("promote: cleaned up %s", d.name)
        except Exception as e:
            logger.warning("promote: failed to clean up %s: %s", d.name, e)


def generate_alias_dirs(agents_dir: Path) -> list[Path]:
    """Generate alias directories from ``promote_agents`` in preset.yaml.

    For each entry in the ``promote_agents`` mapping the function creates
    an alias directory named ``{parent}_{agent}`` containing:

    * ``.adk/preset.yaml`` — records the resolved ``agent_path``
    * ``__init__.py`` — dynamically imports and re-exports ``root_agent``
    * ``.auto_generated`` — sentinel for :func:`cleanup_auto_generated`
    * ``.gitignore`` — prevents the directory from being tracked

    Returns:
        List of generated directory paths.
    """
    generated: list[Path] = []

    if not agents_dir.is_dir():
        return generated

    for agent_dir in sorted(agents_dir.iterdir()):
        if not agent_dir.is_dir():
            continue
        preset_path = find_preset_file(agent_dir)
        if preset_path is None:
            continue

        try:
            data = load_raw_yaml(preset_path)
        except Exception as e:
            logger.warning("promote: failed to read %s: %s", preset_path, e)
            continue

        promote_agents = data.get("promote_agents")
        if not promote_agents:
            continue

        parent_name = agent_dir.name

        # promote_agents is a mapping: { agent_name: { module?, initial_state?, ... } }
        for agent_name, entry in promote_agents.items():
            entry = entry or {}
            module = entry.get("module", "agent")
            alias_state = entry.get("initial_state")
            alias_name = f"{parent_name}_{agent_name}"

            alias_dir = agents_dir / alias_name

            # Skip if a manually-created directory already exists
            if alias_dir.exists() and not (alias_dir / _AUTO_GENERATED_MARKER).exists():
                logger.warning(
                    "promote: skipping %s — directory already exists (not auto-generated)",
                    alias_name,
                )
                continue

            # Create the alias directory structure
            adk_dir = alias_dir / ".adk"
            adk_dir.mkdir(parents=True, exist_ok=True)

            # Sentinel marker
            (alias_dir / _AUTO_GENERATED_MARKER).write_text(
                f"Auto-generated by adkx from {parent_name}\n"
            )

            # Ignore everything inside this directory
            (alias_dir / ".gitignore").write_text("*\n", encoding="utf-8")

            # Resolve the fully-qualified agent path
            agent_path = f"{parent_name}.{module}.{agent_name}"

            # Write .adk/preset.yaml
            alias_preset: dict = {"agent_path": agent_path}
            state = alias_state or data.get("initial_state")
            if state:
                alias_preset["initial_state"] = state
            with open(adk_dir / "preset.yaml", "w", encoding="utf-8") as f:
                yaml.dump(alias_preset, f, default_flow_style=False, allow_unicode=True)

            # Write __init__.py that dynamically imports the target agent
            init_content = textwrap.dedent("""\
                import importlib
                import yaml
                from pathlib import Path

                _preset_path = Path(__file__).parent / ".adk" / "preset.yaml"
                with open(_preset_path) as f:
                    _config = yaml.safe_load(f)

                _parts = _config["agent_path"].rsplit(".", 1)
                _module = importlib.import_module(_parts[0])
                root_agent = getattr(_module, _parts[1])
            """)
            (alias_dir / "__init__.py").write_text(init_content, encoding="utf-8")

            generated.append(alias_dir)
            logger.info("promote: generated alias %s -> %s", alias_name, agent_path)

    return generated
